### ISSUE TITLE
The size of tensor a (310) must match the size of tensor b (320) at non-singleton dimension 2

### ISSUE THREAD

**Issue by zhouzhenneng** [ZiqiaoPeng/SyncTalk#105]
[INFO] ===== finished face tracking =====
[INFO] ===== extract flow =====
num data:  8365
load done
  0%|                                                                                                                                    | 0/8365 [00:00<?, ?it/s]/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                    | 0/8365 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data_utils/UNFaceFlow/test_flow.py", line 62, in <module>
    predict(data)
  File "data_utils/UNFaceFlow/test_flow.py", line 31, in predict
    flow = model(src_crop_im, tar_crop_im, src_im, tar_im, crop_param)
  File "/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/SyncTalk/data_utils/UNFaceFlow/models/network_test_flow.py", line 83, in forward
    flow_fw_crop = (scale2 - scale1) * grid_crop + scale2 * flow_fw_crop
RuntimeError: The size of tensor a (310) must match the size of tensor b (320) at non-singleton dimension 2
Traceback (most recent call last):
  File "data_utils/process.py", line 477, in <module>
    extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir)
  File "data_utils/process.py", line 295, in extract_flow
    flow = np.load(os.path.join(flow_dir, '{:d}_{:d}.npy'.format(ref_id, valid_img_ids[i])))
  File "/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/share/SyncTalk/train/data/youzhe_stand_brown_720_head/flow_result/2_0.npy'

为什么在数据预处理的阶段会出现这个错误，应该怎么解决

**Comment by Jason-cs18** [comment]
原始视频要裁成512x512，否则容易报这个错

**Comment by ZiqiaoPeng** [comment]
It is only suitable for 512*512 resolution and the face is real and clear.
