### ISSUE TITLE
python main.py --test error

### ISSUE THREAD

**Issue by Rane2021** [ZiqiaoPeng/SyncTalk#107]
python main.py data/Xinw2 --workspace model/trial_xinw2_hubert -O --test --asr_model hubert --portrait --aud ./data/sun.wav

[ERROR] If do not use Audio Visual Encoder, replace it with the npy file path.
Traceback (most recent call last):
  File "/data3/2024-projects/19_talkface/01_SyncTalk/SyncTalk_V2/main.py", line 186, in <module>
    test_set = NeRFDataset(opt, device=device, type='train')
  File "/data3/2024-projects/19_talkface/01_SyncTalk/SyncTalk_V2/nerf_triplane/provider.py", line 235, in __init__
    aud_features = torch.from_numpy(aud_features)
UnboundLocalError: local variable 'aud_features' referenced before assignment

**Comment by Rane2021** [comment]
解决了，手动添加 hubert 提特征！nice work!

**Comment by faiejir** [comment]
> 解决了，手动添加 hubert 提特征！nice work!

请问怎么提特征啊
