### ISSUE TITLE
deepspeech error

### ISSUE THREAD

**Issue by G-force78** [ZiqiaoPeng/SyncTalk#117]
Traceback (most recent call last):
  File "/content/SyncTalk/data_utils/deepspeech_features/extract_ds_features.py", line 131, in <module>
    main()
  File "/content/SyncTalk/data_utils/deepspeech_features/extract_ds_features.py", line 107, in main
    extract_features(
  File "/content/SyncTalk/data_utils/deepspeech_features/extract_ds_features.py", line 80, in extract_features
    conv_audios_to_deepspeech(
  File "/content/SyncTalk/data_utils/deepspeech_features/deepspeech_features.py", line 53, in conv_audios_to_deepspeech
    ds_features = pure_conv_audio_to_deepspeech(
  File "/content/SyncTalk/data_utils/deepspeech_features/deepspeech_features.py", line 144, in pure_conv_audio_to_deepspeech
    x=audio.astype(np.float),
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by G-force78** [comment]
SyncTalk/workspace/10.npy: Invalid data found when processing input

**Comment by hereTac** [comment]
> File "/content/SyncTalk/data_utils/deepspeech_features/deepspeech_features.py", line 14
Change the code as below way

 `# x=audio.astype(np.float),`
`x=audio.astype(float),`

**Comment by hereTac** [comment]
> SyncTalk/workspace/10.npy: Invalid data found when processing input Then processed another from scratch and got same error
> 
> parser.add_argument('--aud', type=str, default='', help="audio source (empty will load the default, else should be a path to a npy file)")
> 
> aud_ds.npy: Invalid data found when processing input
> 
> sorry but this implemenattion is just full of errors every step of the way

ISSUE  #113
