### ISSUE TITLE
执行python main.py data/May --workspace model/trial_may -O --iters 60000 --asr_model ave报错“fps"

### ISSUE THREAD

**Issue by xdujinsiyu** [ZiqiaoPeng/SyncTalk#137]
![报错](https://github.com/ZiqiaoPeng/SyncTalk/assets/121628461/da6aa866-b48e-4d85-823b-50e41daddcf6)
==> Start Test, save results to model/trial_may/results
100% 552/553 [00:24<00:00, 21.50it/s]Traceback (most recent call last):
  File "main.py", line 261, in <module>
    trainer.test(test_loader)
  File "/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py", line 1098, in test
    imageio.mimwrite(os.path.join(save_path, f'{name}.mp4'), all_preds, fps=25, quality=8, macro_block_size=1)
  File "/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/imageio/v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/imageio/plugins/tifffile_v3.py", line 224, in write
    self._fh.write(image, **kwargs)
TypeError: write() got an unexpected keyword argument 'fps'
100% 553/553 [00:25<00:00, 22.04it/s]

**Comment by CSZHK** [comment]
pip install -r requirements 重装下，有库没装全
