### ISSUE TITLE
No faces were detected.

### ISSUE THREAD

**Issue by ahkimkoo** [ZiqiaoPeng/SyncTalk#163]
```bash
0% 0/82 [00:00<?, ?it/s]/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py:1078: RuntimeWarning: invalid value encountered in cast
  pred = (pred * 255).astype(np.uint8)
/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py:1084: RuntimeWarning: invalid value encountered in cast
  pred_depth = (pred_depth * 255).astype(np.uint8)
100% 82/82 [00:13<00:00,  6.24it/s]==> Finished Test.
100% 82/82 [00:14<00:00,  5.72it/s]
++> Evaluate at epoch 72 ...
  0% 0/82 [00:00<?, ?it/s]/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py:580: RuntimeWarning: invalid value encountered in cast
  inp = (inp * 255).astype(np.uint8)
/root/autodl-tmp/vms/synctalk/lib/python3.8/site-packages/face_alignment/api.py:147: UserWarning: No faces were detected.
  warnings.warn("No faces were detected.")
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    trainer.evaluate(test_loader)
  File "/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py", line 1039, in evaluate
    self.evaluate_one_epoch(loader, name)
  File "/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py", line 1403, in evaluate_one_epoch
    metric.update(preds, truths)
  File "/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py", line 589, in update
    lms_pred = self.get_landmarks(preds)
  File "/root/autodl-tmp/SyncTalk/nerf_triplane/utils.py", line 560, in get_landmarks
    lms = self.predictor.get_landmarks(img)[-1]
TypeError: 'NoneType' object is not subscriptable
  0% 0/82 [00:01<?, ?it/s]
```

**Comment by yyjjww** [comment]
the same question，help！ @ZiqiaoPeng

**Comment by SuroshAhmadZobair** [comment]
make sure your input video is 512x512 and the speaker is in the center.

**Comment by yyjjww** [comment]
meet the requirement，i sure，help me please！




护
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZiqiaoPeng/SyncTalk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 晚上11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZiqiaoPeng/SyncTalk] No faces were detected. (Issue #163)





 
make sure your input video is 512x512 and the speaker is in the center.
