### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by XxsStrongest** [ZiqiaoPeng/SyncTalk#196]
[INFO] ===== extract semantics from data/123/ori_imgs to data/123/parsing =====
[INFO] loading model...
 21%|████████████████████████                                                                                         | 710/3339 [00:46<02:51, 15.37it/s]
Traceback (most recent call last):
  File "/data/workpace/SyncTalk/data_utils/face_parsing/test.py", line 148, in <module>
    evaluate(respth=args.respath, dspth=args.imgpath, cp=args.modelpath)
  File "/data/workpace/SyncTalk/data_utils/face_parsing/test.py", line 139, in evaluate
    vis_parsing_maps(image, parsing, stride=1, save_im=True, save_path=osp.join(respth, image_path), img_size=ori_size)
  File "/data/workpace/SyncTalk/data_utils/face_parsing/test.py", line 73, in vis_parsing_maps
    y_min = np.min(bottom_face_coords[:, 1])
  File "<__array_function__ internals>", line 200, in amin
  File "/data/workpace/SyncTalk/.conda/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/data/workpace/SyncTalk/.conda/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

数据预处理的人体分隔阶段出现错误，就问题看来是某一帧出现了问题，不知道是什么导致的

**Comment by Ap1075** [comment]
@XxsStrongest could you find a solution?
