### ISSUE TITLE
[extract flow] FileNotFoundError: [Errno 2] No such file or directory: 'data/xxx\\flow_result\\2_1.npy'

### ISSUE THREAD

**Issue by linhcentrio** [ZiqiaoPeng/SyncTalk#224]
[INFO] ===== extract flow =====
num data:  7667
load done
  0%|                                                                                         | 0/7667 [00:00<?, ?it/s]D:\Talking_head\SyncTalk\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
 74%|█████████████████████████████████████████████████████████▊                    | 5685/7667 [17:12<06:00,  5.51it/s]
Traceback (most recent call last):
  File "D:\Talking_head\SyncTalk\data_utils\UNFaceFlow\test_flow.py", line 62, in <module>
    predict(data)
  File "D:\Talking_head\SyncTalk\data_utils\UNFaceFlow\test_flow.py", line 34, in predict
    save_flow_numpy(os.path.join(save_path, os.path.basename(
  File "D:\Talking_head\SyncTalk\data_utils\UNFaceFlow\test_flow.py", line 17, in save_flow_numpy
    np.save(filename, flow_input)
  File "<__array_function__ internals>", line 200, in save
  File "D:\Talking_head\SyncTalk\venv\lib\site-packages\numpy\lib\npyio.py", line 522, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "D:\Talking_head\SyncTalk\venv\lib\site-packages\numpy\lib\format.py", line 723, in write_array
    array.tofile(fp)
OSError: 1843200 requested and 0 written
Traceback (most recent call last):
  File "D:\Talking_head\SyncTalk\data_utils\process.py", line 477, in <module>
    extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir)
  File "D:\Talking_head\SyncTalk\data_utils\process.py", line 295, in extract_flow
    flow = np.load(os.path.join(flow_dir, '{:d}_{:d}.npy'.format(ref_id, valid_img_ids[i])))
  File "D:\Talking_head\SyncTalk\venv\lib\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/Mr_Dung\\flow_result\\2_1.npy'

**Comment by Eikwang** [comment]
需要将数据集中的wav音频转化为npy文件
