### ISSUE TITLE
error on windows 10: extract blendshape "IndexError: list index out of range"

### ISSUE THREAD

**Issue by linhcentrio** [ZiqiaoPeng/SyncTalk#225]
frame= 7667 fps=361 q=1.0 Lsize=N/A time=00:05:06.64 bitrate=N/A speed=14.4x
[INFO] ===== extracted images =====
[INFO] ===== extract semantics from data\Mr_Dung\ori_imgs to data\Mr_Dung\parsing =====
[INFO] loading model...
  0%|                                                                                                                                                                     | 0/15334 [00:00<?, ?it/s]D:\Talking_head\SyncTalk\data_utils\face_parsing\test.py:128: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  image = img.resize((512, 512), Image.BILINEAR)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15334/15334 [28:10<00:00,  9.07it/s]
[INFO] ===== extracted semantics =====
[INFO] ===== extract background image from data\Mr_Dung\ori_imgs =====
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 384/384 [28:41<00:00,  4.48s/it]
[INFO] ===== extracted background image =====
[INFO] ===== extract torso and gt images for data\Mr_Dung =====
 46%|███████████████████████████████████████████████████████████████████████                                                                                    | 3514/7667 [16:17<19:38,  3.52it/s]D:\Talking_head\SyncTalk\venv\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\Talking_head\SyncTalk\venv\lib\site-packages\numpy\core\_methods.py:184: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7667/7667 [36:02<00:00,  3.55it/s]
[INFO] ===== extracted torso and gt images =====
[INFO] ===== extract face landmarks from data\Mr_Dung\ori_imgs =====
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7667/7667 [22:21<00:00,  5.71it/s]
[INFO] ===== extracted face landmarks =====
[INFO] ===== perform face tracking =====
500 3.9871985912323 -301.3426513671875
550 4.183141708374023 -316.8758239746094
600 4.275426387786865 -331.374267578125
650 4.426002502441406 -344.96746826171875
700 4.5654683113098145 -357.76580810546875
750 4.9640421867370605 -369.86773681640625
800 4.837891578674316 -381.45428466796875
850 4.971717357635498 -392.611083984375
900 5.1748199462890625 -403.0872497558594
950 5.193976402282715 -413.14373779296875
1000 5.422350883483887 -422.8393859863281
1050 5.403739929199219 -432.215576171875
1100 5.652215957641602 -441.3194885253906
1150 5.594884395599365 -450.1877746582031
1200 5.6582112312316895 -458.85540771484375
1250 5.843262672424316 -467.3542175292969
1300 5.794276714324951 -475.7117614746094
1350 5.923620700836182 -483.96405029296875
1400 5.9138689041137695 -492.1175842285156
1450 5.986741542816162 -500.2021484375
500 4.384185314178467 -301.348876953125
face tracking params saved
[INFO] ===== finished face tracking =====
[INFO] ===== extract flow =====
num data:  7667
load done
  0%|                                                                                                                                                                      | 0/7667 [00:00<?, ?it/s]D:\Talking_head\SyncTalk\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7667/7667 [22:25<00:00,  5.70it/s]
bundle adjustment params saved
[INFO] ===== extract blendshape =====
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1726505790.269383    4036 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
npy file not exists: Mr_Dung
fps: 25.003260727794444
frame_count: 7668
total: 7668
videoPath:data\Mr_Dung\Mr_Dung.mp4 fps:25.003260727794444,k
  0%|▊                                                                                                                                                            | 38/7668 [00:03<12:59,  9.78it/s]Traceback (most recent call last):
  File "D:\Talking_head\SyncTalk\data_utils\blendshape_capture\main.py", line 86, in <module>
    infer_bs(args.path)
  File "D:\Talking_head\SyncTalk\data_utils\blendshape_capture\main.py", line 63, in infer_bs
    result.face_blendshapes[0]]
IndexError: list index out of range
  0%|▊                                                                                                                                                            | 38/7668 [00:04<13:50,  9.19it/s]
[INFO] ===== save transforms =====
[INFO] ===== finished saving transforms =====

**Comment by CaptainDP** [comment]
Linux same problem：
git version：
commit cd12d541aaa6b663f85a5c242fde6b6cbe33c2e5 (HEAD -> main, origin/main, origin/HEAD)
Author: Ziqiao Peng <93774583+ZiqiaoPeng@users.noreply.github.com>
Date:   Wed Aug 28 16:06:17 2024 +0800


[INFO] ===== extract blendshape =====
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1729244417.046022    4438 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1729244417.069351    4470 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.67), renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
W0000 00:00:1729244417.069972    4438 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
npy file not exists: demo
fps: 30.0
frame_count: 1234
total: 1234
videoPath:xunfei_mingxuan.mp4 fps:30.0,k
  4%|█████▌                                                                                                                                | 51/1234 [00:08<03:13,  6.11it/s]Traceback (most recent call last):
  File "data_utils/blendshape_capture/main.py", line 86, in <module>
    infer_bs(args.path)
  File "data_utils/blendshape_capture/main.py", line 63, in infer_bs
    result.face_blendshapes[0]]
IndexError: list index out of range
  4%|█████▌                                                                                                                                | 51/1234 [00:08<03:14,  6.09it/s]
[INFO] ===== save transforms =====
[INFO] ===== finished saving transforms =====

**Comment by smalldaidai** [comment]
我曾碰到过一次这个问题，我怀疑原因是因为我用的视频时长过短，后面用了要求的4-5分钟时长的视频后，就没有这个问题了
