### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/May/transforms_val.json'

### ISSUE THREAD

**Issue by saba99** [ZiqiaoPeng/SyncTalk#34]
Namespace(path='data/May', O=True, test=True, test_train=False, data_range=[0, -1], workspace='model/trial_may', seed=0, iters=200000, lr=0.01, lr_net=0.001, ckpt='latest', num_rays=65536, cuda_ray=True, max_steps=16, num_steps=16, upsample_steps=0, update_extra_interval=16, max_ray_batch=4096, warmup_step=10000, amb_aud_loss=1, amb_eye_loss=1, unc_loss=1, lambda_amb=0.1, pyramid_loss=0, fp16=True, bg_img='', fbg=False, exp_eye=True, fix_eye=-1, smooth_eye=False, bs_area='upper', torso_shrink=0.8, color_space='srgb', preload=0, bound=1, scale=4, offset=[0, 0, 0], dt_gamma=0.00390625, min_near=0.05, density_thresh=10, density_thresh_torso=0.01, patch_size=1, init_lips=False, finetune_lips=False, smooth_lips=False, torso=False, head_ckpt='', gui=False, W=450, H=450, radius=3.35, fovy=21.24, max_spp=1, att=2, aud='', emb=False, portrait=False, ind_dim=4, ind_num=20000, ind_dim_torso=8, amb_dim=2, part=False, part2=False, train_camera=False, smooth_path=False, smooth_path_window=7, asr=False, asr_wav='', asr_play=False, asr_model='ave', asr_save_feats=False, fps=50, l=10, m=50, r=10)
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
100% 233M/233M [00:01<00:00, 244MB/s]
Loading model from: /usr/local/lib/python3.10/dist-packages/lpips/weights/v0.1/alex.pth
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /root/.cache/torch/hub/checkpoints/s3fd-619a316812.pth
100% 85.7M/85.7M [14:43<00:00, 102kB/s]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/2DFAN4-cd938726ad.zip" to /root/.cache/torch/hub/checkpoints/2DFAN4-cd938726ad.zip
100% 91.9M/91.9M [00:04<00:00, 21.7MB/s]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: /usr/local/lib/python3.10/dist-packages/lpips/weights/v0.1/alex.pth
[INFO] Trainer: ngp | 2024-03-11_15-57-00 | cuda | fp16 | model/trial_may
[INFO] #parameters: 768165
[INFO] Loading latest checkpoint ...
[INFO] Latest checkpoint is model/trial_may/checkpoints/ngp_ep0019.pth
[INFO] loaded model.
[INFO] load at epoch 19, global step 104880
[WARN] Failed to load optimizer.
[INFO] loaded scheduler.
[INFO] loaded scaler.
Traceback (most recent call last):
  File "/content/drive/MyDrive/SyncTalk/main.py", line 192, in <module>
    test_loader = NeRFDataset(opt, device=device, type='test').dataloader()
  File "/content/drive/MyDrive/SyncTalk/nerf_triplane/provider.py", line 127, in __init__
    with open(os.path.join(self.root_path, f'transforms_{_split}.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/May/transforms_val.json'

**Comment by KavinduKariyawasam** [comment]
place the May.zip in the data folder as in the Data preparation

**Comment by ZiqiaoPeng** [comment]
Thank you for helping me reply.
