### ISSUE TITLE
UserWarning: No faces were detected.

### ISSUE THREAD

**Issue by WoJiaoFuXiaoYun** [ZiqiaoPeng/SyncTalk#44]
When I follow the instructions in the readme to run the evaluation code, an error occurs.How should I solve it?

> python main.py data/May --workspace model/trial_may -O --test --asr_model ave

```
Namespace(H=450, O=True, W=450, amb_aud_loss=1, amb_dim=2, amb_eye_loss=1, asr=False, asr_model='ave', asr_play=False, asr_save_feats=False, asr_wav='', att=2, aud='', bg_img='', bound=1, bs_area='upper', ckpt='latest', color_space='srgb', cuda_ray=True, data_range=[0, -1], density_thresh=10, density_thresh_torso=0.01, dt_gamma=0.00390625, emb=False, exp_eye=True, fbg=False, finetune_lips=False, fix_eye=-1, fovy=21.24, fp16=True, fps=50, gui=False, head_ckpt='', ind_dim=4, ind_dim_torso=8, ind_num=20000, init_lips=False, iters=200000, l=10, lambda_amb=0.1, lr=0.01, lr_net=0.001, m=50, max_ray_batch=4096, max_spp=1, max_steps=16, min_near=0.05, num_rays=65536, num_steps=16, offset=[0, 0, 0], part=False, part2=False, patch_size=1, path='data/May', portrait=False, preload=0, pyramid_loss=0, r=10, radius=3.35, scale=4, seed=0, smooth_eye=False, smooth_lips=False, smooth_path=False, smooth_path_window=7, test=True, test_train=False, torso=False, torso_shrink=0.8, train_camera=False, unc_loss=1, update_extra_interval=16, upsample_steps=0, warmup_step=10000, workspace='model/trial_may')
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/sg/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/sg/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/sg/miniconda3/envs/synctalk/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/home/sg/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/sg/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/sg/miniconda3/envs/synctalk/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
[INFO] Trainer: ngp | 2024-03-20_03-36-57 | cuda | fp16 | model/trial_may
[INFO] #parameters: 768165
[INFO] Loading latest checkpoint ...
[WARN] No checkpoint found, model randomly initialized.
[INFO] load 553 test frames.
[INFO] load  aud_features: torch.Size([6072, 1, 512])
Loading test data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 553/553 [00:00<00:00, 6888.24it/s]
[INFO] eye_area: -0.06423357874155045 - 0.9898659586906433
==> Start Test, save results to model/trial_may/results
100% 551/553 [00:12<00:00, 44.98it/s]==> Finished Test.
100% 553/553 [00:14<00:00, 38.84it/s]
++> Evaluate at epoch 0 ...
  0% 0/553 [00:00<?, ?it/s]/home/sg/miniconda3/envs/synctalk/lib/python3.8/site-packages/face_alignment/api.py:147: UserWarning: No faces were detected.
  warnings.warn("No faces were detected.")
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    trainer.evaluate(test_loader)
  File "/home/sg/github/SyncTalk/nerf_triplane/utils.py", line 1039, in evaluate
    self.evaluate_one_epoch(loader, name)
  File "/home/sg/github/SyncTalk/nerf_triplane/utils.py", line 1403, in evaluate_one_epoch
    metric.update(preds, truths)
  File "/home/sg/github/SyncTalk/nerf_triplane/utils.py", line 589, in update
    lms_pred = self.get_landmarks(preds)
  File "/home/sg/github/SyncTalk/nerf_triplane/utils.py", line 560, in get_landmarks
    lms = self.predictor.get_landmarks(img)[-1]
TypeError: 'NoneType' object is not subscriptable
  0% 0/553 [00:00<?, ?it/s]
  ```

**Comment by ZiqiaoPeng** [comment]
`[WARN] No checkpoint found, model randomly initialized.`
Please put the model in the correct folder.

**Comment by schxnhxlz** [comment]
Hi I got the same error. The model is in the right folder. what could it be?
<img width="337" alt="Screenshot 2024-04-29 at 11 26 32" src="https://github.com/ZiqiaoPeng/SyncTalk/assets/58291636/5ed411f2-b96d-4122-814d-0573c61b135d">

**Comment by Jason-cs18** [comment]
> Hi I got the same error. The model is in the right folder. what could it be? <img alt="Screenshot 2024-04-29 at 11 26 32" width="337" src="https://private-user-images.githubusercontent.com/58291636/326389698-5ed411f2-b96d-4122-814d-0573c61b135d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4ODA1MDgsIm5iZiI6MTcxNDg4MDIwOCwicGF0aCI6Ii81ODI5MTYzNi8zMjYzODk2OTgtNWVkNDExZjItYjk2ZC00MTIyLTgxNGQtMDU3M2M2MWIxMzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDAzMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNjBlN2EzMzY2MWIxMGM4MmE4ZTZjZWU0MGNhMmZlM2FmNDYwN2IxOGY1MWU0Y2VlYmJiNGUxYjhiMWY0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SqDaaqWDRcvF8N5uRuZeiwawcMZn9pOVgNH0nKP5mpg">

I have pulled the latest repo, but I met the same issue when I trained on my custom dataset. Did you find a solution?

My model folder is as follows
```bash
model/trial_chinese5/
├── checkpoints
├── log_ngp.txt
├── opt.txt
├── run
└── validation
```

My training command is `CUDA_VISIBLE_DEVICES=1 python main.py data/Chinese5 --workspace model/trial_chinese5 -O --iters 60000 --asr_model ave`

**Comment by einsqing** [comment]
不稳定，ernerf 都一次训练成功的视频，用 synctalk 训练成功率 50%

**Comment by Tiandishihua** [comment]
> 不稳定，ernerf 都一次训练成功的视频，用 synctalk 训练成功率 50%

请问你找到解决办法吗？总是莫名其妙的终端训练

**Comment by Tiandishihua** [comment]
> 不稳定，ernerf 都一次训练成功的视频，用 synctalk 训练成功率 50%

请问你找到解决办法吗？总是莫名其妙终止训练。

**Comment by G-force78** [comment]
No solution to this? Maybe its detection size? No idea where to change that though

**Comment by nldhuyen0047** [comment]
Hi, I have encountered the same error with you, I am wondering if you fixed this code? Therefore, could you please show me how to solve this code? 

Thank you so much.
