### ISSUE TITLE
IndexError: index 3104 is out of bounds for dimension 0 with size 3054

### ISSUE THREAD

**Issue by piwawa** [ZiqiaoPeng/SyncTalk#76]
```
$ sh ./scripts/train_may.sh
Namespace(path='data/lizzi', O=True, test=False, test_train=False, data_range=[0, -1], workspace='model/trial_lizzi', seed=0, iters=60000, lr=0.01, lr_net=0.001, ckpt='latest', num_rays=65536, cuda_ray=True, max_steps=16, num_steps=16, upsample_steps=0, update_extra_interval=16, max_ray_batch=4096, warmup_step=10000, amb_aud_loss=1, amb_eye_loss=1, unc_loss=1, lambda_amb=0.1, pyramid_loss=0, fp16=True, bg_img='', fbg=False, exp_eye=True, fix_eye=-1, smooth_eye=False, bs_area='upper', torso_shrink=0.8, color_space='srgb', preload=1, bound=1, scale=4, offset=[0, 0, 0], dt_gamma=0.00390625, min_near=0.05, density_thresh=10, density_thresh_torso=0.01, patch_size=1, init_lips=False, finetune_lips=False, smooth_lips=False, torso=False, head_ckpt='', gui=False, W=450, H=450, radius=3.35, fovy=21.24, max_spp=1, att=2, aud='data/lizzi/aud.wav', emb=False, portrait=False, ind_dim=4, ind_num=20000, ind_dim_torso=8, amb_dim=2, part=False, part2=False, train_camera=False, smooth_path=False, smooth_path_window=7, asr=False, asr_wav='', asr_play=False, asr_model='ave', asr_save_feats=False, fps=50, l=10, m=50, r=10)
[INFO] load 3054 train frames.
[INFO] load data/lizzi/aud.wav aud_features: torch.Size([3361, 1, 512])
Loading train data: 100%|██████████████████████████████████████████████████████████████████| 3054/3054 [00:25<00:00, 117.91it/s]
[INFO] eye_area: -0.04632186517119408 - 0.8404859304428101
[INFO] Trainer: ngp | 2024-04-30_14-31-37 | cuda | fp16 | model/trial_lizzi
[INFO] #parameters: 768165
[INFO] Loading latest checkpoint ...
[WARN] No checkpoint found, model randomly initialized.
[INFO] load 100 val frames.
[INFO] load data/lizzi/aud.wav aud_features: torch.Size([3361, 1, 512])
Loading val data: 100%|██████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 153.19it/s]
[INFO] eye_area: -0.039902642369270325 - 0.7581108808517456
[INFO] max_epoch = 20
==> Start Training Epoch 1, lr=0.001000 ...
loss=0.0823 (0.1449), lr=0.001000: :   0% 15/3054 [00:01<06:47,  7.47it/s]Traceback (most recent call last):
  File "/home/bingo06/AIGC/SyncTalk/main.py", line 249, in <module>
    trainer.train(train_loader, valid_loader, max_epochs)
  File "/home/bingo06/AIGC/SyncTalk/nerf_triplane/utils.py", line 1025, in train
    self.train_one_epoch(train_loader)
  File "/home/bingo06/AIGC/SyncTalk/nerf_triplane/utils.py", line 1290, in train_one_epoch
    self.model.update_extra_state()
  File "/home/bingo06/miniconda3/envs/cu118/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bingo06/AIGC/SyncTalk/nerf_triplane/renderer.py", line 439, in update_extra_state
    eye = self.eye_area[[rand_idx]].to(self.density_bitfield.device) # [1, 1]
IndexError: index 3104 is out of bounds for dimension 0 with size 3054
loss=0.0823 (0.1449), lr=0.001000: :   1% 16/3054 [00:01<06:17,  8.05it/s]
```

为啥用自己视频训练，每次都会出现 IndexError，明明用的训练视频提取的原音频，但是音频特征的维度居然和帧数不一致？？

```
[INFO] load data/lizzi/aud.wav aud_features: torch.Size([3361, 1, 512])
[INFO] load 3054 train frames.
```

**Comment by ZiqiaoPeng** [comment]
train frames只有10/11的数据集，音频特征加载的全部特征，只会用前面一部分，你的总帧数应该是3360左右。

**Comment by reputationMK** [comment]
您好，请问这个indexerror您是如何解决的呢，我也出现了这样的问题：    area = bs[f['img_id']]
IndexError: index 6480 is out of bounds for axis 0 with size 6480，十分感谢！@piwawa

**Comment by yuanmaitian** [comment]
> 您好，请问这个indexerror您是如何解决的呢，我也出现了这样的问题： area = bs[f['img_id']] IndexError: index 6480 is out of bounds for axis 0 with size 6480，十分感谢！@piwawa

我也出现了这个问题，在python main.py data/kanghui/ --workspace model/trial_kanghui/ -O --iters 60000 --asr_model ave
时：
Traceback (most recent call last):
  File "/root/workspace/main.py", line 256, in <module>
    test_loader = NeRFDataset(opt, device=device, type='test').dataloader()
  File "/root/workspace/nerf_triplane/provider.py", line 361, in __init__
    area = bs[f['img_id']]
IndexError: index 6319 is out of bounds for axis 0 with size 6319
请问您解决了吗？

**Comment by AyushUnleashed** [comment]
To solve this just make sure your input video is 25 fps @yuanmaitian  @Zhiyuan624 @piwawa
