### ISSUE TITLE
size not match

### ISSUE THREAD

**Issue by ThetaRgo** [ZiqiaoPeng/SyncTalk#83]
the video size must 320?

  File "/d2/SyncTalk/data_utils/UNFaceFlow/models/network_test_flow.py", line 83, in forward
    flow_fw_crop = (scale2 - scale1) * grid_crop + scale2 * flow_fw_crop
RuntimeError: The size of tensor a (270) must match the size of tensor b (320) at non-singleton dimension 2
Traceback (most recent call last):
  File "/d2/SyncTalk/data_utils/process.py", line 461, in <module>
    extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir)
  File "/d2/SyncTalk/data_utils/process.py", line 282, in extract_flow
    flow = np.load(os.path.join(flow_dir, '{:d}_{:d}.npy'.format(ref_id, valid_img_ids[i])))
  File "/home/gpuserver/.conda/envs/ernerf/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/tianliang/flow_result/2_0.npy'

**Comment by ZiqiaoPeng** [comment]
This should be that task 9 is not running correctly, please check the output of the process.py.

**Comment by zhouzhenneng** [comment]
所以应该怎么解决这个问题，我也在数据预处理阶段出现了：
[INFO] ===== finished face tracking =====
[INFO] ===== extract flow =====
num data:  8365
load done
  0%|                                                                                                                                    | 0/8365 [00:00<?, ?it/s]/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                                                                    | 0/8365 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data_utils/UNFaceFlow/test_flow.py", line 62, in <module>
    predict(data)
  File "data_utils/UNFaceFlow/test_flow.py", line 31, in predict
    flow = model(src_crop_im, tar_crop_im, src_im, tar_im, crop_param)
  File "/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/SyncTalk/data_utils/UNFaceFlow/models/network_test_flow.py", line 83, in forward
    flow_fw_crop = (scale2 - scale1) * grid_crop + scale2 * flow_fw_crop
RuntimeError: The size of tensor a (310) must match the size of tensor b (320) at non-singleton dimension 2
Traceback (most recent call last):
  File "data_utils/process.py", line 477, in <module>
    extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir)
  File "data_utils/process.py", line 295, in extract_flow
    flow = np.load(os.path.join(flow_dir, '{:d}_{:d}.npy'.format(ref_id, valid_img_ids[i])))
  File "/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/share/SyncTalk/train/data/youzhe_stand_brown_720_head/flow_result/2_0.npy'

**Comment by DestoryVIP** [comment]
不知道对不对，只需要把参数里的crop_width和crop_height设置为宽高的一半就行
