### ISSUE TITLE
2_0.npy

### ISSUE THREAD

**Issue by MtYCNN** [ZiqiaoPeng/SyncTalk#85]
[INFO] ===== extract flow =====
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Traceback (most recent call last):
  File "data_utils/process.py", line 461, in <module>
    extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir)
  File "data_utils/process.py", line 282, in extract_flow
    flow = np.load(os.path.join(flow_dir, '{:d}_{:d}.npy'.format(ref_id, valid_img_ids[i])))
  File "/home/pai/envs/sync/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/nv/flow_result/2_0.npy'

May I ask what the problem is? The previous output is normal, why is an error reported at this step。

**Comment by MtYCNN** [comment]
> [INFO] ===== extract flow ===== Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library. Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it. Traceback (most recent call last): File "data_utils/process.py", line 461, in extract_flow(base_dir, ori_imgs_dir, mask_imgs_dir, flow_dir) File "data_utils/process.py", line 282, in extract_flow flow = np.load(os.path.join(flow_dir, '{:d}_{:d}.npy'.format(ref_id, valid_img_ids[i]))) File "/home/pai/envs/sync/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: 'data/nv/flow_result/2_0.npy'
> 
> May I ask what the problem is? The previous output is normal, why is an error reported at this step。

解决办法：
 export MKL_THREADING_LAYER=GNU
