### ISSUE TITLE
Deepspeech training.

### ISSUE THREAD

**Issue by hasanshahid5678** [ZiqiaoPeng/SyncTalk#96]
Hi Author, thanks for the wonderful work. I am having some issue when I try to preprocess the data. It is giving the following tracebacks.
[INFO] ===== extract audio labels for data/apd/aud.wav =====
Traceback (most recent call last):
  File "data_utils/deepspeech_features/extract_ds_features.py", line 10, in <module>
    from deepspeech_features import conv_audios_to_deepspeech
  File "/home/europa/work/video_deep_fake/SyncTalk/data_utils/deepspeech_features/deepspeech_features.py", line 13, in <module>
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'

I have already installed the tensorflow using pip install tensorflow-gpu==2.8.1 and pulled the latest code.
After I ignored this error in preprocessing and started training using deepspeech, the following error  occured.
[INFO] load 5094 train frames.
Traceback (most recent call last):
  File "main.py", line 219, in <module>
    train_loader = NeRFDataset(opt, device=device, type='train').dataloader()
  File "/home/europa/work/video_deep_fake/SyncTalk/nerf_triplane/provider.py", line 166, in __init__
    aud_features = np.load(os.path.join(self.root_path, 'aud_ds.npy'))
  File "/opt/conda/envs/synctalk/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/apd/aud_ds.npy'

**Comment by ZiqiaoPeng** [comment]
You can try to reset the conda environment.
