### ISSUE TITLE
Use deepspeech as asr_model result checkpoint occur size mismatch 

### ISSUE THREAD

**Issue by hereTac** [ZiqiaoPeng/SyncTalk#97]
As the README's tips, use the deepspeech to train the custom video. Command as below thing.
`python main.py data/head-bg  --workspace model/trail_head-bg/  -O --iters 100000 --finetune_lips --patch_size 64 --asr_model deepspeech`. Uset the result latest 143 checkpoint to inference with target audio, occur error message 

`python main.py data/head-bg --workspace model/trail_head-bg -O --test --test_train --asr_model deepspeech --portra
it --aud ./80s.mp3`

```
 
Namespace(H=450, O=True, W=450, amb_aud_loss=1, amb_dim=2, amb_eye_loss=1, asr=False, asr_model='ave', asr_play=False, asr_save_feats=False, asr_wav='', att=2, aud='./80s.mp3', bg_img='', bound=1, bs_area='upper', ckpt='latest', color_space='srgb', cuda_ray=True, data_range=[0, -1], density_thresh=10, density_thresh_torso=0.01, dt_gamma=0.00390625, emb=False, exp_eye=True, fbg=False, finetune_lips=False, fix_eye=-1, fovy=21.24, fp16=True, fps=50, gui=False, head_ckpt='', ind_dim=4, ind_dim_torso=8, ind_num=20000, init_lips=False, iters=200000, l=10, lambda_amb=0.1, lr=0.01, lr_net=0.001, m=50, max_ray_batch=4096, max_spp=1, max_steps=16, min_near=0.05, num_rays=65536, num_steps=16, offset=[0, 0, 0], part=False, part2=False, patch_size=1, path='data/head-bg', portrait=True, preload=0, pyramid_loss=0, r=10, radius=3.35, scale=4, seed=0, smooth_eye=False, smooth_lips=False, smooth_path=False, smooth_path_window=7, test=True, test_train=True, torso=False, torso_shrink=0.8, train_camera=False, unc_loss=1, update_extra_interval=16, upsample_steps=0, warmup_step=10000, workspace='model/trail_head-bg')
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
 warnings.warn(
/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
 warnings.warn(msg)
Loading model from: /root/miniconda3/envs/synctalk/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
 warnings.warn(
/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
 warnings.warn(msg)
Loading model from: /root/miniconda3/envs/synctalk/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
[INFO] Trainer: ngp | 2024-05-07_15-42-30 | cuda | fp16 | model/trail_head-bg
[INFO] #parameters: 768165
[INFO] Loading latest checkpoint ...
[INFO] Latest checkpoint is model/trail_head-bg/checkpoints/ngp_ep0143.pth
Traceback (most recent call last):
 File "main.py", line 183, in 
  trainer = Trainer('ngp', opt, model, device=device, workspace=opt.workspace, criterion=criterion, fp16=opt.fp16, metrics=metrics, use_checkpoint=opt.ckpt)
 File "/mnt/aistack/xinz.zhang/SyncTalk/nerf_triplane/utils.py", line 735, in __init__
  self.load_checkpoint()
 File "/mnt/aistack/xinz.zhang/SyncTalk/nerf_triplane/utils.py", line 1532, in load_checkpoint
  missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint_dict['model'], strict=False)
 File "/root/miniconda3/envs/synctalk/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
  raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
    size mismatch for audio_net.encoder_fc1.0.weight: copying a param with shape torch.Size([64, 64]) from checkpoint, the shape in current model is torch.Size([256, 512]).
    size mismatch for audio_net.encoder_fc1.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
    size mismatch for audio_net.encoder_fc1.2.weight: copying a param with shape torch.Size([32, 64]) from checkpoint, the shape in current model is torch.Size([128, 256]).
    size mismatch for audio_net.encoder_fc1.2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([128]). 
```

**Comment by husthzy** [comment]
The two audio features cannot be mixed

**Comment by ZiqiaoPeng** [comment]
It seems that you are using different asr models, please make sure you use the same one. If you use deepspeech, use the npy file.

**Comment by hereTac** [comment]
@ZiqiaoPeng Hi. AS the README. 
| Inference with target audio.  If do not use Audio Visual Encoder, replace wav with the npy file path.
If use asr model ave, just use the audio file path. For deepspeech and hubert how to generate the target audio's npy file?

**Comment by hereTac** [comment]
e.g. Use asr model deepspeech to train the custom-made video, This will generate an aud_ds.npy file. 
`replace wav with the npy file path.` So you're not referring to the aud_ds.npy file, are you? It is generated from the custom-made video. So how can I get the npy file for my desired audio?

**Comment by hereTac** [comment]
#104

**Comment by hereTac** [comment]
data_utils/deepspeech_features/README.md
